include:
  - project: eng/gpr/gpr
    file: /.gitlab-ci-shared.yml

stages:
  - build
  - test

build:
  extends: .job_template
  stage: build
  script:
    - setup_repos gprconfig_kb gpr

    # Tune to use our build & test plan
    - anod tune --plan /tmp/gpr/.ci.plan

    # Build using anod
    - anod run build

    # and save the gprbuild install
    - tar czf $CI_PROJECT_DIR/gprbuild.tar.gz -C $SANDBOX/$HOST/gprbuild/ install/
  artifacts:
    paths:
      - gprbuild.tar.gz

test_gprbuild:
  extends: .test_template
  script:
    - setup_repos gprbuild-internal
    - install_packages gnatall
    - run_testsuite gprbuild -QAdaCC++_Auto test_gprbuild
  artifacts:
    when:
      always
    paths:
      - testgprbuild_result.xml
    reports:
      junit: testgprbuild_result.xml
